stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - qusaielwazir_tag      # <-- change to your runner's tag
  script:
    - cd Backend/Users        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package

maven-test:
  stage: maventest
  tags:
    - qusaielwazir_tag     # <-- change to your runner's tag
  script:
    - cd Backend/Users       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
