stages:
  - androidbuild
  - androidtest 
  
android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - nayma_tag                   # <-- change to your runner's tag
  before_script:                    # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/testingUI/gradlew
  script:
    - cd Frontend/testingUI                   # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew build

android-test:
   image: afirefly/android-ci:java17
   stage: androidtest
   tags:
    - nayma_tag                  # <-- change to your runner's tag
   before_script:                   # change 'Frontend' to where you have 'gradlew'
     - export GRADLE_USER_HOME=`pwd`/.gradle
     - chmod +x ./Frontend/testingUI/gradlew
   script:
     - cd Frontend/testingUI                  # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
     - ./gradlew test
